# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'ffi'

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = true

    config.vm.hostname = 'test26.um.local'
    config.vm.network "private_network", ip: '192.168.7.226'
    config.vm.provider "virtualbox" do |v|
        v.memory = 12288
        v.cpus = 2
        v.name = 'test26.um.local'
    end

    if FFI::Platform::IS_MAC
        # configure host updater plugin - https://github.com/cogitatio/vagrant-hostsupdater
        config.hostsupdater.aliases = ["test26"]

        # configure VirtualBox Guest Additions plugin - https://github.com/dotless-de/vagrant-vbguest
        config.vbguest.auto_update = true
        config.vbguest.no_remote = true
        config.vbguest.no_install = false
    end

    config.vm.provision "shell", inline: "service network restart", run: "always"

    # provision VM
    config.vm.provision "file", source: "hosts", destination: "/tmp/install/hosts"
    config.vm.provision "file", source: "blueprint.json", destination: "/tmp/install/blueprint.json"
    config.vm.provision "file", source: "create-cluster.json", destination: "/tmp/install/create-cluster.json"
    config.vm.provision "Install", type: "shell", keep_color: "true", path: "install.sh"
    config.vm.provision "Ambari Details", type: "shell", inline: "echo 'Ambari URL is http://test26.um.local:8080 or http://test26:8080 or http://192.168.7.226:8080'", run: "always"
end
